CREATE TABLE IF NOT EXISTS cars (
    id BIGINT PRIMARY KEY,
    mark_id INTEGER NOT NULL DEFAULT 0,
    model_id INTEGER NOT NULL DEFAULT 0,
    mark_name TEXT NOT NULL DEFAULT '',
    model_name TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    usd INTEGER NOT NULL DEFAULT 0,
    uah INTEGER NOT NULL DEFAULT 0,
    eur INTEGER NOT NULL DEFAULT 0,
    link_to_view TEXT NOT NULL DEFAULT '',
    vin TEXT NOT NULL DEFAULT '',
    add_date TEXT NOT NULL DEFAULT '',
    update_date TEXT NOT NULL DEFAULT '',
    expire_date TEXT NOT NULL DEFAULT '',
    location_city TEXT NOT NULL DEFAULT '',
    year INTEGER NOT NULL DEFAULT 0,
    race_int INTEGER NOT NULL DEFAULT 0,
    description TEXT NOT NULL DEFAULT '',
    fuel_name TEXT NOT NULL DEFAULT '',
    gearbox_name TEXT NOT NULL DEFAULT '',
    category_id INTEGER NOT NULL DEFAULT 0,
    is_sold BOOLEAN NOT NULL DEFAULT FALSE,
    state_id INTEGER NOT NULL DEFAULT 0,
    city_id INTEGER NOT NULL DEFAULT 0,
    region_name TEXT NOT NULL DEFAULT '',
    dealer_id INTEGER NOT NULL DEFAULT 0,
    dealer_name TEXT NOT NULL DEFAULT '',
    technical_condition_id INTEGER NOT NULL DEFAULT 0,
    technical_condition_name TEXT NOT NULL DEFAULT '',
    color_name TEXT NOT NULL DEFAULT '',
    exchange_possible BOOLEAN NOT NULL DEFAULT FALSE,
    auction_possible BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
